//! Core data types for the provider abstraction layer.
//!
//! This module defines the message, tool, capability, and metadata types shared
//! by all AI provider backends, as well as the extended thinking-mode and model
//! capability types introduced in Phase 9.
//!
//! # Type Hierarchy
//!
//! - [`Role`] / [`Message`] — conversation primitives
//! - [`Tool`] / [`ToolCall`] / [`FunctionCall`] — tool-calling support
//! - [`ProviderMetadata`] / [`ProviderCapabilities`] — provider-level aggregates
//! - [`ModelMetadata`] / [`ModelCapabilities`] — per-model capability records
//! - [`ThinkingMode`] — reasoning budget control
//! - [`CredentialStatus`] / [`MetadataSource`] — resolution metadata

use serde::{Deserialize, Serialize};

// ---------------------------------------------------------------------------
// Conversation primitives
// ---------------------------------------------------------------------------

/// Role of a message participant in a conversation thread.
///
/// Matches the role taxonomy used by OpenAI-compatible chat completion APIs.
///
/// # Examples
///
/// ```
/// use xzardgz::providers::types::Role;
///
/// let role = Role::User;
/// assert_eq!(role, Role::User);
/// assert_ne!(role, Role::Assistant);
/// ```
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub enum Role {
    /// A system-level instruction message that sets model behavior.
    System,
    /// A message originating from the human user.
    User,
    /// A response generated by the AI assistant.
    Assistant,
    /// A tool invocation result message sent back to the model.
    Tool,
}

/// A single message in a conversation thread.
///
/// Messages form an ordered list passed to the provider for chat completion.
/// Use the [`Message::system`], [`Message::user`], and [`Message::assistant`]
/// constructors for the common cases.
///
/// # Examples
///
/// ```
/// use xzardgz::providers::types::{Message, Role};
///
/// let msg = Message::user("Explain Rust lifetimes.");
/// assert_eq!(msg.role, Role::User);
/// assert_eq!(msg.content, "Explain Rust lifetimes.");
/// assert!(msg.name.is_none());
/// assert!(msg.tool_calls.is_none());
/// ```
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Message {
    /// The role of the message author.
    pub role: Role,
    /// The textual content of the message.
    pub content: String,
    /// Optional display name for the author (useful in multi-participant chats).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// Tool calls requested by the assistant in this message, if any.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub tool_calls: Option<Vec<ToolCall>>,
    /// Tool call ID when this message is a tool result, correlating with a
    /// prior [`ToolCall`] from the assistant.
    pub tool_call_id: Option<String>,
}

impl Message {
    /// Creates a new [`Role::System`] message.
    ///
    /// # Examples
    ///
    /// ```
    /// use xzardgz::providers::types::{Message, Role};
    ///
    /// let msg = Message::system("You are a helpful assistant.");
    /// assert_eq!(msg.role, Role::System);
    /// assert_eq!(msg.content, "You are a helpful assistant.");
    /// ```
    pub fn system(content: impl Into<String>) -> Self {
        Self {
            role: Role::System,
            content: content.into(),
            name: None,
            tool_calls: None,
            tool_call_id: None,
        }
    }

    /// Creates a new [`Role::User`] message.
    ///
    /// # Examples
    ///
    /// ```
    /// use xzardgz::providers::types::{Message, Role};
    ///
    /// let msg = Message::user("Hello, world!");
    /// assert_eq!(msg.role, Role::User);
    /// assert_eq!(msg.content, "Hello, world!");
    /// ```
    pub fn user(content: impl Into<String>) -> Self {
        Self {
            role: Role::User,
            content: content.into(),
            name: None,
            tool_calls: None,
            tool_call_id: None,
        }
    }

    /// Creates a new [`Role::Assistant`] message.
    ///
    /// # Examples
    ///
    /// ```
    /// use xzardgz::providers::types::{Message, Role};
    ///
    /// let msg = Message::assistant("I can help with that.");
    /// assert_eq!(msg.role, Role::Assistant);
    /// assert_eq!(msg.content, "I can help with that.");
    /// ```
    pub fn assistant(content: impl Into<String>) -> Self {
        Self {
            role: Role::Assistant,
            content: content.into(),
            name: None,
            tool_calls: None,
            tool_call_id: None,
        }
    }
}

// ---------------------------------------------------------------------------
// Tool definitions
// ---------------------------------------------------------------------------

/// A tool call requested by the assistant within a message.
///
/// Each call has a unique `id` that must be included in the corresponding
/// tool result message to allow the model to correlate responses.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ToolCall {
    /// Unique identifier for this tool call instance.
    pub id: String,
    /// The function invocation details for this call.
    pub function: FunctionCall,
}

/// Details of a function invocation within a [`ToolCall`].
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct FunctionCall {
    /// The name of the function to invoke.
    pub name: String,
    /// The function arguments serialized as a JSON object string.
    pub arguments: String,
}

/// A tool definition made available to the model during a completion request.
///
/// Providers that support tool use present these definitions to the model,
/// allowing it to emit structured [`ToolCall`] objects in assistant messages.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Tool {
    /// The tool's canonical name (used in function calls).
    pub name: String,
    /// Human-readable description of what the tool does.
    pub description: String,
    /// JSON Schema object describing the tool's input parameters.
    pub parameters: serde_json::Value,
}

// ---------------------------------------------------------------------------
// Provider-level metadata
// ---------------------------------------------------------------------------

/// Aggregate metadata describing an AI provider backend.
///
/// Returned by [`Provider::metadata`][crate::providers::base::Provider::metadata]
/// to describe the provider's identity and aggregate capabilities.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ProviderMetadata {
    /// The canonical name of this provider (e.g., `"openai"`, `"ollama"`).
    pub name: String,
    /// List of model identifiers available from this provider.
    pub models: Vec<String>,
    /// Aggregate capability flags across all models on this provider.
    pub capabilities: ProviderCapabilities,
}

/// Provider-level capability flags.
///
/// Represents the aggregate capabilities advertised by the provider as a
/// whole. For per-model accuracy use [`ModelCapabilities`] instead.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ProviderCapabilities {
    /// Whether any model on this provider supports streaming responses.
    pub streaming: bool,
    /// Whether any model on this provider supports tool/function calling.
    pub tools: bool,
    /// Whether any model on this provider supports vision (image) inputs.
    pub vision: bool,
}

// ---------------------------------------------------------------------------
// Thinking mode
// ---------------------------------------------------------------------------

/// Thinking/reasoning mode for AI providers that support extended reasoning.
///
/// Controls whether and how deeply a provider should "think" (chain-of-thought
/// reasoning) before composing a final response.  The resolver maps `Auto` to
/// a concrete level at runtime based on model capabilities.
///
/// # Examples
///
/// ```
/// use xzardgz::providers::types::ThinkingMode;
///
/// assert!(!ThinkingMode::None.requests_thinking());
/// assert!(ThinkingMode::Low.requests_thinking());
/// assert!(ThinkingMode::Low.requires_thinking_support());
/// assert!(!ThinkingMode::Auto.requires_thinking_support());
/// assert_eq!(ThinkingMode::Medium.budget_tokens(), Some(8_000));
/// assert_eq!(ThinkingMode::None.budget_tokens(), None);
/// ```
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, Default)]
pub enum ThinkingMode {
    /// Never perform any extended reasoning; respond directly.
    #[default]
    None,
    /// Use extended reasoning if the model supports it; skip silently if not.
    Auto,
    /// Request approximately 2,000 tokens of reasoning budget.
    Low,
    /// Request approximately 8,000 tokens of reasoning budget.
    Medium,
    /// Request approximately 16,000 tokens of reasoning budget.
    High,
    /// Request approximately 32,000 tokens of reasoning budget.
    ExtraHigh,
}

impl ThinkingMode {
    /// Returns `true` if this mode requests any form of thinking.
    ///
    /// Both `Auto` and all explicit levels return `true`.  Only `None` returns
    /// `false`.
    ///
    /// # Examples
    ///
    /// ```
    /// use xzardgz::providers::types::ThinkingMode;
    ///
    /// assert!(!ThinkingMode::None.requests_thinking());
    /// assert!(ThinkingMode::Auto.requests_thinking());
    /// assert!(ThinkingMode::High.requests_thinking());
    /// ```
    pub fn requests_thinking(&self) -> bool {
        !matches!(self, Self::None)
    }

    /// Returns `true` if an explicit thinking level was requested.
    ///
    /// Explicit levels (`Low`, `Medium`, `High`, `ExtraHigh`) indicate the
    /// caller expects full thinking support from the selected model.  `None`
    /// and `Auto` return `false` — they either opt-out or degrade gracefully.
    ///
    /// # Examples
    ///
    /// ```
    /// use xzardgz::providers::types::ThinkingMode;
    ///
    /// assert!(ThinkingMode::Low.requires_thinking_support());
    /// assert!(ThinkingMode::ExtraHigh.requires_thinking_support());
    /// assert!(!ThinkingMode::Auto.requires_thinking_support());
    /// assert!(!ThinkingMode::None.requires_thinking_support());
    /// ```
    pub fn requires_thinking_support(&self) -> bool {
        matches!(
            self,
            Self::Low | Self::Medium | Self::High | Self::ExtraHigh
        )
    }

    /// Returns the approximate token budget for providers that accept a budget.
    ///
    /// Returns `None` for [`ThinkingMode::None`] and [`ThinkingMode::Auto`],
    /// indicating the caller or provider should choose the budget.
    ///
    /// # Examples
    ///
    /// ```
    /// use xzardgz::providers::types::ThinkingMode;
    ///
    /// assert_eq!(ThinkingMode::None.budget_tokens(), None);
    /// assert_eq!(ThinkingMode::Auto.budget_tokens(), None);
    /// assert_eq!(ThinkingMode::Low.budget_tokens(), Some(2_000));
    /// assert_eq!(ThinkingMode::Medium.budget_tokens(), Some(8_000));
    /// assert_eq!(ThinkingMode::High.budget_tokens(), Some(16_000));
    /// assert_eq!(ThinkingMode::ExtraHigh.budget_tokens(), Some(32_000));
    /// ```
    pub fn budget_tokens(&self) -> Option<u32> {
        match self {
            Self::None | Self::Auto => None,
            Self::Low => Some(2_000),
            Self::Medium => Some(8_000),
            Self::High => Some(16_000),
            Self::ExtraHigh => Some(32_000),
        }
    }
}

// ---------------------------------------------------------------------------
// Per-model capability record
// ---------------------------------------------------------------------------

/// Capability flags and context-window size for a single AI model.
///
/// Unlike [`ProviderCapabilities`], which reflects provider-level aggregates,
/// this struct captures per-model accuracy and is used by the model resolver
/// during selection and thinking-mode resolution.
///
/// # Examples
///
/// ```
/// use xzardgz::providers::types::ModelCapabilities;
///
/// let caps = ModelCapabilities::default();
/// assert!(!caps.supports_tools);
/// assert_eq!(caps.context_window_tokens, 4096);
/// ```
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ModelCapabilities {
    /// Whether this model supports tool/function calling.
    pub supports_tools: bool,
    /// Whether this model supports structured output (e.g., JSON schema enforcement).
    pub supports_structured_output: bool,
    /// Whether this model supports extended chain-of-thought reasoning.
    pub supports_thinking: bool,
    /// Whether this model supports streaming response delivery.
    pub supports_streaming: bool,
    /// Whether this model accepts image inputs (vision).
    pub supports_vision: bool,
    /// Approximate context window size in tokens.
    pub context_window_tokens: u32,
}

impl Default for ModelCapabilities {
    /// Returns conservative defaults: all capabilities disabled, 4,096-token
    /// context window.
    fn default() -> Self {
        Self {
            supports_tools: false,
            supports_structured_output: false,
            supports_thinking: false,
            supports_streaming: false,
            supports_vision: false,
            context_window_tokens: 4096,
        }
    }
}

/// Full metadata record for a single AI model.
///
/// Holds the model's provider-assigned identifier, an optional human-readable
/// display name, and its capability flags.  Used by the model resolver during
/// selection and thinking-mode resolution.
///
/// # Examples
///
/// ```
/// use xzardgz::providers::types::{ModelCapabilities, ModelMetadata};
///
/// let caps = ModelCapabilities::default();
/// let meta = ModelMetadata::new("gpt-4o-mini", caps);
/// assert_eq!(meta.id, "gpt-4o-mini");
/// assert_eq!(meta.display_name, Some("gpt-4o-mini".to_string()));
/// ```
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ModelMetadata {
    /// Provider-assigned model identifier (e.g., `"gpt-4o-mini"`).
    pub id: String,
    /// Optional human-readable display name shown in UI and reports.
    pub display_name: Option<String>,
    /// Capability flags for this specific model.
    pub capabilities: ModelCapabilities,
}

impl ModelMetadata {
    /// Constructs a `ModelMetadata` with `display_name` initialised equal to `id`.
    ///
    /// # Arguments
    ///
    /// * `id` - The provider-assigned model identifier.
    /// * `capabilities` - The capability flags for this model.
    ///
    /// # Examples
    ///
    /// ```
    /// use xzardgz::providers::types::{ModelCapabilities, ModelMetadata};
    ///
    /// let meta = ModelMetadata::new("claude-3-5-sonnet", ModelCapabilities::default());
    /// assert_eq!(meta.id, "claude-3-5-sonnet");
    /// assert_eq!(meta.display_name, Some("claude-3-5-sonnet".to_string()));
    /// ```
    pub fn new(id: impl Into<String>, capabilities: ModelCapabilities) -> Self {
        let id = id.into();
        let display_name = Some(id.clone());
        Self {
            id,
            display_name,
            capabilities,
        }
    }
}

// ---------------------------------------------------------------------------
// Resolution metadata enums
// ---------------------------------------------------------------------------

/// Credential presence status for a provider.
///
/// Reflects whether credentials are available without making any network
/// calls to validate them against the provider API.
///
/// # Examples
///
/// ```
/// use xzardgz::providers::types::CredentialStatus;
///
/// let status = CredentialStatus::Present;
/// assert_eq!(status, CredentialStatus::Present);
/// assert_ne!(status, CredentialStatus::Missing);
/// ```
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub enum CredentialStatus {
    /// Credentials found in env var or keyring. Not validated against the API.
    Present,
    /// No credentials found in any configured location.
    Missing,
    /// Credential status cannot be determined (e.g., keyring service unavailable).
    Unknown,
}

/// Source of model capability metadata used during resolution.
///
/// Records the provenance of [`ModelMetadata`] in a `ResolvedModel` for
/// observability and debugging purposes.
///
/// # Examples
///
/// ```
/// use xzardgz::providers::types::MetadataSource;
///
/// assert_eq!(MetadataSource::Static, MetadataSource::Static);
/// assert_ne!(MetadataSource::Remote, MetadataSource::Degraded);
/// ```
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub enum MetadataSource {
    /// Metadata fetched live from the provider API.
    Remote,
    /// Metadata from compiled-in static tables.
    Static,
    /// Metadata is incomplete or stale; execution continues in degraded mode.
    Degraded,
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;

    // ------------------------------------------------------------------
    // ThinkingMode::requests_thinking
    // ------------------------------------------------------------------

    #[test]
    fn test_thinking_mode_none_requests_thinking_returns_false() {
        assert!(!ThinkingMode::None.requests_thinking());
    }

    #[test]
    fn test_thinking_mode_auto_requests_thinking_returns_true() {
        assert!(ThinkingMode::Auto.requests_thinking());
    }

    #[test]
    fn test_thinking_mode_explicit_levels_request_thinking_returns_true() {
        assert!(ThinkingMode::Low.requests_thinking());
        assert!(ThinkingMode::Medium.requests_thinking());
        assert!(ThinkingMode::High.requests_thinking());
        assert!(ThinkingMode::ExtraHigh.requests_thinking());
    }

    // ------------------------------------------------------------------
    // ThinkingMode::requires_thinking_support
    // ------------------------------------------------------------------

    #[test]
    fn test_thinking_mode_none_requires_thinking_support_returns_false() {
        assert!(!ThinkingMode::None.requires_thinking_support());
    }

    #[test]
    fn test_thinking_mode_auto_requires_thinking_support_returns_false() {
        assert!(!ThinkingMode::Auto.requires_thinking_support());
    }

    #[test]
    fn test_thinking_mode_explicit_levels_require_thinking_support_returns_true() {
        assert!(ThinkingMode::Low.requires_thinking_support());
        assert!(ThinkingMode::Medium.requires_thinking_support());
        assert!(ThinkingMode::High.requires_thinking_support());
        assert!(ThinkingMode::ExtraHigh.requires_thinking_support());
    }

    // ------------------------------------------------------------------
    // ThinkingMode::budget_tokens
    // ------------------------------------------------------------------

    #[test]
    fn test_thinking_mode_budget_tokens_none_returns_none() {
        assert_eq!(ThinkingMode::None.budget_tokens(), None);
    }

    #[test]
    fn test_thinking_mode_budget_tokens_auto_returns_none() {
        assert_eq!(ThinkingMode::Auto.budget_tokens(), None);
    }

    #[test]
    fn test_thinking_mode_budget_tokens_low_returns_two_thousand() {
        assert_eq!(ThinkingMode::Low.budget_tokens(), Some(2_000));
    }

    #[test]
    fn test_thinking_mode_budget_tokens_medium_returns_eight_thousand() {
        assert_eq!(ThinkingMode::Medium.budget_tokens(), Some(8_000));
    }

    #[test]
    fn test_thinking_mode_budget_tokens_high_returns_sixteen_thousand() {
        assert_eq!(ThinkingMode::High.budget_tokens(), Some(16_000));
    }

    #[test]
    fn test_thinking_mode_budget_tokens_extra_high_returns_thirty_two_thousand() {
        assert_eq!(ThinkingMode::ExtraHigh.budget_tokens(), Some(32_000));
    }

    #[test]
    fn test_thinking_mode_default_is_none_variant() {
        let mode: ThinkingMode = Default::default();
        assert_eq!(mode, ThinkingMode::None);
    }

    // ------------------------------------------------------------------
    // ModelCapabilities::default
    // ------------------------------------------------------------------

    #[test]
    fn test_model_capabilities_default_all_flags_are_false() {
        let caps = ModelCapabilities::default();
        assert!(!caps.supports_tools);
        assert!(!caps.supports_structured_output);
        assert!(!caps.supports_thinking);
        assert!(!caps.supports_streaming);
        assert!(!caps.supports_vision);
    }

    #[test]
    fn test_model_capabilities_default_context_window_is_4096() {
        let caps = ModelCapabilities::default();
        assert_eq!(caps.context_window_tokens, 4096);
    }

    // ------------------------------------------------------------------
    // ModelMetadata::new
    // ------------------------------------------------------------------

    #[test]
    fn test_model_metadata_new_sets_id_correctly() {
        let meta = ModelMetadata::new("gpt-4o-mini", ModelCapabilities::default());
        assert_eq!(meta.id, "gpt-4o-mini");
    }

    #[test]
    fn test_model_metadata_new_sets_display_name_equal_to_id() {
        let meta = ModelMetadata::new("gpt-4o-mini", ModelCapabilities::default());
        assert_eq!(meta.display_name, Some("gpt-4o-mini".to_string()));
    }

    #[test]
    fn test_model_metadata_new_stores_capabilities() {
        let caps = ModelCapabilities {
            supports_tools: true,
            supports_thinking: true,
            context_window_tokens: 128_000,
            ..ModelCapabilities::default()
        };
        let meta = ModelMetadata::new("claude-3-5-sonnet", caps);
        assert!(meta.capabilities.supports_tools);
        assert!(meta.capabilities.supports_thinking);
        assert_eq!(meta.capabilities.context_window_tokens, 128_000);
    }

    // ------------------------------------------------------------------
    // CredentialStatus
    // ------------------------------------------------------------------

    #[test]
    fn test_credential_status_present_equals_present() {
        assert_eq!(CredentialStatus::Present, CredentialStatus::Present);
    }

    #[test]
    fn test_credential_status_present_not_equal_to_missing() {
        assert_ne!(CredentialStatus::Present, CredentialStatus::Missing);
    }

    #[test]
    fn test_credential_status_unknown_not_equal_to_missing() {
        assert_ne!(CredentialStatus::Unknown, CredentialStatus::Missing);
    }

    #[test]
    fn test_credential_status_unknown_not_equal_to_present() {
        assert_ne!(CredentialStatus::Unknown, CredentialStatus::Present);
    }

    // ------------------------------------------------------------------
    // MetadataSource
    // ------------------------------------------------------------------

    #[test]
    fn test_metadata_source_remote_equals_remote() {
        assert_eq!(MetadataSource::Remote, MetadataSource::Remote);
    }

    #[test]
    fn test_metadata_source_static_not_equal_to_degraded() {
        assert_ne!(MetadataSource::Static, MetadataSource::Degraded);
    }

    #[test]
    fn test_metadata_source_remote_not_equal_to_static() {
        assert_ne!(MetadataSource::Remote, MetadataSource::Static);
    }

    // ------------------------------------------------------------------
    // Message constructors
    // ------------------------------------------------------------------

    #[test]
    fn test_message_system_sets_system_role_and_content() {
        let msg = Message::system("You are helpful.");
        assert_eq!(msg.role, Role::System);
        assert_eq!(msg.content, "You are helpful.");
        assert!(msg.name.is_none());
        assert!(msg.tool_calls.is_none());
        assert!(msg.tool_call_id.is_none());
    }

    #[test]
    fn test_message_user_sets_user_role_and_content() {
        let msg = Message::user("What is 2+2?");
        assert_eq!(msg.role, Role::User);
        assert_eq!(msg.content, "What is 2+2?");
    }

    #[test]
    fn test_message_assistant_sets_assistant_role_and_content() {
        let msg = Message::assistant("The answer is 4.");
        assert_eq!(msg.role, Role::Assistant);
        assert_eq!(msg.content, "The answer is 4.");
    }

    // ------------------------------------------------------------------
    // Role equality
    // ------------------------------------------------------------------

    #[test]
    fn test_role_system_equals_system() {
        assert_eq!(Role::System, Role::System);
    }

    #[test]
    fn test_role_user_not_equal_to_assistant() {
        assert_ne!(Role::User, Role::Assistant);
    }
}
