//! Pre-AI scan findings.
//!
//! Defines [`FindingSeverity`] and [`ScanFinding`], which represent
//! structured observations produced by pattern-matching hooks before
//! any AI analysis stage runs.

use serde::{Deserialize, Serialize};

/// Severity level of a pre-AI scan finding.
///
/// Variants are ordered from least severe to most severe so that the derived
/// [`Ord`] implementation reflects impact: `Info < Low < Medium < High < Critical`.
/// This means a `Critical` finding compares greater than an `Info` finding,
/// allowing callers to sort or filter by threshold with standard comparison
/// operators.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Serialize, Deserialize)]
pub enum FindingSeverity {
    /// Purely informational; no immediate risk.
    Info,
    /// Low impact; informational in most contexts.
    Low,
    /// Moderate impact; should be reviewed.
    Medium,
    /// High impact; requires prompt attention.
    High,
    /// Immediately exploitable or catastrophic impact.
    Critical,
}

impl FindingSeverity {
    /// Returns the lowercase string representation of the severity.
    ///
    /// # Returns
    ///
    /// A static string slice: `"info"`, `"low"`, `"medium"`, `"high"`,
    /// or `"critical"`.
    ///
    /// # Examples
    ///
    /// ```
    /// use xzardgz::scanner::findings::FindingSeverity;
    ///
    /// assert_eq!(FindingSeverity::Critical.as_str(), "critical");
    /// assert_eq!(FindingSeverity::Info.as_str(), "info");
    /// ```
    pub fn as_str(&self) -> &'static str {
        match self {
            FindingSeverity::Info => "info",
            FindingSeverity::Low => "low",
            FindingSeverity::Medium => "medium",
            FindingSeverity::High => "high",
            FindingSeverity::Critical => "critical",
        }
    }

    /// Returns the uppercase label for display use.
    ///
    /// # Returns
    ///
    /// A static string slice: `"INFO"`, `"LOW"`, `"MEDIUM"`, `"HIGH"`,
    /// or `"CRITICAL"`.
    ///
    /// # Examples
    ///
    /// ```
    /// use xzardgz::scanner::findings::FindingSeverity;
    ///
    /// assert_eq!(FindingSeverity::High.label(), "HIGH");
    /// assert_eq!(FindingSeverity::Low.label(), "LOW");
    /// ```
    pub fn label(&self) -> &'static str {
        match self {
            FindingSeverity::Info => "INFO",
            FindingSeverity::Low => "LOW",
            FindingSeverity::Medium => "MEDIUM",
            FindingSeverity::High => "HIGH",
            FindingSeverity::Critical => "CRITICAL",
        }
    }
}

/// A pre-AI finding produced during a repository scan.
///
/// Findings are generated by pattern-matching hooks that run before any AI
/// analysis.  Each finding records the source file, the evidence that
/// triggered it, and a severity classification.
///
/// # Examples
///
/// ```
/// use xzardgz::scanner::findings::{FindingSeverity, ScanFinding};
///
/// let f = ScanFinding::new(
///     "secrets".to_string(),
///     "src/config.rs".to_string(),
///     Some(42),
///     "AWS_SECRET_ACCESS_KEY".to_string(),
///     FindingSeverity::Critical,
/// );
/// assert_eq!(f.kind, "secrets");
/// assert_eq!(f.severity, FindingSeverity::Critical);
/// ```
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ScanFinding {
    /// Category or rule that produced this finding (e.g. `"secrets"`, `"unsafe_rust"`).
    pub kind: String,
    /// Repository-relative path of the file containing the finding.
    pub file: String,
    /// Line number where the finding was observed, if known.
    pub line: Option<u32>,
    /// The text evidence that triggered the finding.
    pub evidence: String,
    /// Severity classification.
    pub severity: FindingSeverity,
}

impl ScanFinding {
    /// Creates a new `ScanFinding`.
    ///
    /// # Arguments
    ///
    /// * `kind` - Category or rule identifier for the finding.
    /// * `file` - Repository-relative path of the affected file.
    /// * `line` - Optional line number of the finding within the file.
    /// * `evidence` - Text snippet or pattern that triggered the finding.
    /// * `severity` - Severity level of the finding.
    ///
    /// # Returns
    ///
    /// A fully populated `ScanFinding`.
    ///
    /// # Examples
    ///
    /// ```
    /// use xzardgz::scanner::findings::{FindingSeverity, ScanFinding};
    ///
    /// let f = ScanFinding::new(
    ///     "unsafe_rust".to_string(),
    ///     "src/ffi.rs".to_string(),
    ///     Some(10),
    ///     "unsafe { ptr::read(p) }".to_string(),
    ///     FindingSeverity::High,
    /// );
    /// assert_eq!(f.line, Some(10));
    /// ```
    pub fn new(
        kind: String,
        file: String,
        line: Option<u32>,
        evidence: String,
        severity: FindingSeverity,
    ) -> Self {
        Self {
            kind,
            file,
            line,
            evidence,
            severity,
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_finding_severity_ordering_info_lt_critical() {
        // Variants are declared Info(0) .. Critical(4); derived Ord gives
        // Info < Low < Medium < High < Critical.
        assert!(FindingSeverity::Info < FindingSeverity::Critical);
        assert!(FindingSeverity::Critical > FindingSeverity::Info);
    }

    #[test]
    fn test_finding_severity_as_str_all_variants() {
        assert_eq!(FindingSeverity::Info.as_str(), "info");
        assert_eq!(FindingSeverity::Low.as_str(), "low");
        assert_eq!(FindingSeverity::Medium.as_str(), "medium");
        assert_eq!(FindingSeverity::High.as_str(), "high");
        assert_eq!(FindingSeverity::Critical.as_str(), "critical");
    }

    #[test]
    fn test_finding_severity_label_all_variants() {
        assert_eq!(FindingSeverity::Info.label(), "INFO");
        assert_eq!(FindingSeverity::Low.label(), "LOW");
        assert_eq!(FindingSeverity::Medium.label(), "MEDIUM");
        assert_eq!(FindingSeverity::High.label(), "HIGH");
        assert_eq!(FindingSeverity::Critical.label(), "CRITICAL");
    }

    #[test]
    fn test_scan_finding_new_sets_all_fields() {
        let f = ScanFinding::new(
            "secrets".to_string(),
            "src/config.rs".to_string(),
            Some(42),
            "AWS_SECRET_ACCESS_KEY".to_string(),
            FindingSeverity::Critical,
        );
        assert_eq!(f.kind, "secrets");
        assert_eq!(f.file, "src/config.rs");
        assert_eq!(f.line, Some(42));
        assert_eq!(f.evidence, "AWS_SECRET_ACCESS_KEY");
        assert_eq!(f.severity, FindingSeverity::Critical);
    }

    #[test]
    fn test_scan_finding_serializes_to_yaml() {
        let f = ScanFinding::new(
            "unsafe_rust".to_string(),
            "src/ffi.rs".to_string(),
            Some(10),
            "unsafe { ptr::read(p) }".to_string(),
            FindingSeverity::High,
        );
        let yaml = serde_yaml::to_string(&f).expect("serialization must succeed");
        assert!(yaml.contains("unsafe_rust"));
        assert!(yaml.contains("src/ffi.rs"));
        assert!(yaml.contains("High") || yaml.contains("high"));
    }
}
